# run with $ cargo +nightly fmt
enum_discrim_align_threshold = 20
fn_single_line = true
force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_granularity="Crate"
max_width = 120
space_after_colon = false
space_before_colon =  false
struct_field_align_threshold = 20
tab_spaces = 2